### ISSUE TITLE
Incorrectly inferring conversion output type

### ISSUE THREAD

**Issue by robotopia** [MWATelescope/mwa_hyperdrive#14]
When trying to convert from RTS to FITS, I get the following behaviour. If my command line is
```
hyperdrive solutions-convert -m example.metafits /dir/containing/rts output.fits
```
then

1. if `output.fits` does not exist, then it tries to write an RTS solution to a folder named `output.fits`
2. if `output.fits` already exists, and is a regular file, then it correctly writes a FITS file.

**Comment by cjordan** [comment]
I'm not sure exactly when this got fixed, but as of v0.2.1, things work as expected. As part of this release, 2ef57f6 fixed even more RTS-solution-reading problems.
