### ISSUE TITLE
Feature request: Allow user to specify dimensions of solutions plots

### ISSUE THREAD

**Issue by robotopia** [MWATelescope/mwa_hyperdrive#20]
The aspect ratio of the plots can sometimes obscure the quality of the solutions.

Example, a solution plotted with hyperdrive...

![hyperdrive_1346649040_sols_phases](https://github.com/MWATelescope/mwa_hyperdrive/assets/13690466/669b13d6-bb78-4405-85c8-935489f3dea2)

...and the same solution plotted with `aocal_plot.py`:

![hyperdrive_1346649040_sols_phase](https://github.com/MWATelescope/mwa_hyperdrive/assets/13690466/43d3cea6-5849-414c-8de6-e07403ab89d8)

These solutions are not great, but you need the extra height to see the wiggles and bumps clearly.

**Comment by d3v-null** [comment]
Interesting! Thanks for the feedback.
We're working on a new release coming soon that will allow you to specify the number of columns and rows in the plot, which should make this a bit nicer, so watch out for that when it's ready. 
https://github.com/MWATelescope/mwa_hyperdrive/blob/6b7dcdb1316719f0732eab702bf865548b473dc7/src/cli/solutions/plot/mod.rs#L47

**Comment by cjordan** [comment]
Fixed by 9ceaea6f
