### ISSUE TITLE
unexpected discontinuity in simulated visibility spectrum

### ISSUE THREAD

**Issue by syoshiura** [MWATelescope/mwa_hyperdrive#23]
Hi, I'm running hyperdrive v0.3.0 to make simulated visibility.

I used command below,
`hyperdrive vis-simulate -s srclist_1093191160_1000.yaml -m 1093191160.metafits  --unity-dipole-gains --veto-threshold 0`

I plot the spectrum of output visibility (picking up a baseline and real part). 
![vis_spectrum](https://github.com/MWATelescope/mwa_hyperdrive/assets/50643795/c8580714-abb9-4a00-95a1-d8a319bff7af)

The visibility has the discontinued spectrum. Is there any proper method to create a smooth visibility?

Thank you.

**Comment by cjordan** [comment]
Hey Shintaro. I could be wrong, but I believe this is a manifestation of the FEE beam; the associated file only defines a beam response every 1.28 MHz. In other words, for a single coarse channel, the beam response will be the same for the first and last fine channels, even though these channel frequencies are nearly 1.28 MHz different.

One thing you can do is use the "interpolated" FEE beam file.  This is on garrawarla at `/astro/mwaeor/software/MWA_embedded_element_pattern_rev2_interp_167_197MHz.h5`.  Note that this only covers the EoR high-band; outside that range, you'll only be using the closest defined frequency, which would make your plot look even worse.

Once you've downloaded it, you can use it by setting `MWA_BEAM_FILE` to the file's path, or by using `--beam-file`.  Please report back with how it went!

P.S. I have a hyperdrive paper draft in the works; it should be submitted within 2 weeks, and I'm happy to share it with you if you're interested.

**Comment by syoshiura** [comment]
Hi Chris, 

Thank you very much for your reply and instruction. 
I performed simulation with the interpolated FEE beam and the discontinuity disappeared.

P.S. That's wonderful! I definitely interested in it!

**Comment by cjordan** [comment]
Great, thanks Shintaro.

**Comment by cjordan** [comment]
For future reference, this interpolated FEE beam file is now hosted here: http://ws.mwatelescope.org/static/MWA_embedded_element_pattern_rev2_interp_167_197MHz.h5
