### ISSUE TITLE
Feature request: allow metafits file format in form of obsid_metafits.fits

### ISSUE THREAD

**Issue by gsleap** [MWATelescope/mwa_hyperdrive#4]
Currently hyperdrive returns the following error when provided with the alternate filename format:
`Error: The specified file '/data/1322254064_metafits.fits' was not a recognised file type.`

Very low priority and easily worked around by renaming to `1322254064.metafits`

**Comment by cjordan** [comment]
Fixed in the latest commit on the di branch.
